### ISSUE TITLE
Grab projectId from `.env`

### ISSUE THREAD

**Issue by safejace** [sanity-io/cross-dataset-duplicator#13]
I have my spaces setup, and did NOT have the `"projectId"` set in sanity.json as I didn't want to commit it to the repo. Which I assumed would be the recommended way.

Looks like duplicator does NOT fallback to a projectId in the `.env` like spaces apparently does. 
Not sure how/why but despite the spaces [docs](https://www.sanity.io/docs/spaces) not mentioning anything about the `projectId` being grabbed from `.env` it seems to work as expected for me.

So when I don't put a `projectId` in the duplicator config, it fails:

![image (3)](https://user-images.githubusercontent.com/97258230/179817880-0b089078-c22c-405c-879b-2b47f8b8586f.png)
![image (2)](https://user-images.githubusercontent.com/97258230/179817885-ed72b4fc-5e3c-480b-a4cc-f08166007a50.png)

**Comment by SimeonGriggs** [comment]
Hey @safejace,

In #14 I've pushed an update now `0.3.5` which will respect the a `SANITY_STUDIO_API_PROJECT_ID` if supplied. 

However the following should be noted
* It is expected that you can check-in a `projectId` to your repo. There's no problem making a `projectId` public as it contains no secure information itself
* Using an environment variable will restrict all duplications to a single project, where writing directly to the `sanity.json` spaces config allows you to specify multiple projects and datasets to migrate between.

**Comment by safejace** [comment]
> * It is expected that you can check-in a `projectId` to your repo. There's no problem making a `projectId` public as it contains no secure information itself

Just to clarify the main reason for wanting this. My team (4 devs) all have our own `projectId` to test/build stuff locally.
Checking our `projectId` to git would just cause issues anytime people created PRs cuz the projectId would change everytime.

This way, everyone just puts their `projectId` in `.env.development` and it "just works"
