### ISSUE TITLE
dlRaw=true results in 401 error

### ISSUE THREAD

**Issue by struct78** [sanity-io/cross-dataset-duplicator#4]
Hi there,

I've just upgraded to version 0.2.0, and noticed that when we attempt to migrate images we get the following error when the plugin attempts to download the raw image:

![](https://i.imgur.com/BsUrfZG.png)

The request is passing the Bearer token okay, but I wonder if there's an issue with the token passed to the CDN?

**Comment by SimeonGriggs** [comment]
This seems to be solved after Resetting the secret and uploading a new one. I'll improve the feedback here in a future relase.

**Comment by struct78** [comment]
Thanks @SimeonGriggs , worked a treat!
